forgot part of the mangos worlddb, tab cleanup

diff --git a/template/s6/etc/cont-init.d/50-installdb-authserver b/template/s6/etc/cont-init.d/50-installdb-authserver
--- a/template/s6/etc/cont-init.d/50-installdb-authserver
+++ b/template/s6/etc/cont-init.d/50-installdb-authserver
@@ -1,7 +1,7 @@
 #!/usr/bin/with-contenv bash
 # Exit if worldserver is not enabled
 if [[ "${AUTHSERVER}" != "true" ]]; then
-        exit 0
+	exit 0
 fi
 
 source /gowowcore/_sql.sh
@@ -18,36 +18,36 @@ SQLwaitUser
 if [[ -e /src/db/Realm/Setup/realmdLoadDB.sql ]]; then
 	# mangos
 	# Install DB if version table is missing
-        if [[ $(SQLuser "SHOW TABLES LIKE 'db_version';" | wc -l) -eq 0 ]]; then
-                echo "[***] Couldn't find db_version table in ${SQL_DB}. Installing LoginDatabaseInfo to ${SQL_DB}."
-                SQLuserFile "/src/db/Realm/Setup/realmdLoadDB.sql"
-        fi
+	if [[ $(SQLuser "SHOW TABLES LIKE 'db_version';" | wc -l) -eq 0 ]]; then
+		echo "[***] Couldn't find db_version table in ${SQL_DB}. Installing LoginDatabaseInfo to ${SQL_DB}."
+		SQLuserFile "/src/db/Realm/Setup/realmdLoadDB.sql"
+	fi
 	DB_VERSION=$(SQLuser "SELECT \`version\` FROM \`db_version\` ORDER BY \`version\` DESC, \`structure\` DESC LIMIT 0,1;")
-        echo "[***] LoginDatabaseInfo installed is ${DB_VERSION}"
+	echo "[***] LoginDatabaseInfo installed is ${DB_VERSION}"
 elif [[ -d /src/server/data/sql/base/db_auth ]]; then
 	# azerothcore
-        for table_sql in $(ls -1 "/src/server/data/sql/base/db_auth/"); do
-                table=${table_sql%.*}
-                if ! SQLexistTable "${table}"; then
-                        SQLuserFile "/src/server/data/sql/base/db_auth/${table_sql}"
-                fi
-        done
+	for table_sql in $(ls -1 "/src/server/data/sql/base/db_auth/"); do
+		table=${table_sql%.*}
+		if ! SQLexistTable "${table}"; then
+			SQLuserFile "/src/server/data/sql/base/db_auth/${table_sql}"
+		fi
+	done
 fi
 
 # Initiate relevant migrations
 if [[ -n "${DB_VERSION}" && -d "/src/db/Realm/Updates/Rel${DB_VERSION}" ]]; then
-        # Mangos
-        echo "[***] Running all available Auth DB updates"
-        for x in $(ls -1 /src/db/Realm/Updates/Rel${DB_VERSION}/*.sql | sort -n); do
-                sed -i 's#DEFINER=`root`@`localhost`##g' "${x}"
-                SQLuserFile "${x}"
-        done
+	# Mangos
+	echo "[***] Running all available Auth DB updates"
+	for x in $(ls -1 /src/db/Realm/Updates/Rel${DB_VERSION}/*.sql | sort -n); do
+		sed -i 's#DEFINER=`root`@`localhost`##g' "${x}"
+		SQLuserFile "${x}"
+	done
 elif [[ -d /src/server/data/sql/updates/db_auth ]]; then
-        # azerothcore
-        echo "[***] Running all available Auth DB updates"
-        for migration_sql in $(ls -1 "/src/server/data/sql/updates/db_auth/"); do
-                SQLuserFile "/src/server/data/sql/updates/db_auth/${migration_sql}"
-        done
+	# azerothcore
+	echo "[***] Running all available Auth DB updates"
+	for migration_sql in $(ls -1 "/src/server/data/sql/updates/db_auth/"); do
+		SQLuserFile "/src/server/data/sql/updates/db_auth/${migration_sql}"
+	done
 fi
 
 # Clean out default accounts, replace with our default "admin:admin" user
@@ -62,10 +62,10 @@ if [[ -e /src/db/Realm/Setup/realmdLoadDB.sql ]]; then
 	)
 	for entry in ${entries[@]}; do
 		regex="^([^,]+),([^,]+),([^,]+)"
-	        if [[ ${entry} =~ $regex ]]; then
-	                U_ID=${BASH_REMATCH[1]}
-	                U_NAME=${BASH_REMATCH[2]}
-                	U_HASH=${BASH_REMATCH[3]}
+		if [[ ${entry} =~ $regex ]]; then
+			U_ID=${BASH_REMATCH[1]}
+			U_NAME=${BASH_REMATCH[2]}
+			U_HASH=${BASH_REMATCH[3]}
 			SQLuser "DELETE FROM \`account\` WHERE \`id\`=${U_ID} AND \`username\`='${U_NAME}' AND \`sha_pass_hash\`='${U_HASH}' AND \`sessionkey\`='' AND \`last_login\`='';"
 		fi
 	done
@@ -88,10 +88,10 @@ elif [[ -d /src/server/data/sql/base/db_auth ]]; then
 	)
 	for entry in ${entries[@]}; do
 		regex="^([^,]+),([^,]+),([^,]+)"
-	        if [[ ${entry} =~ $regex ]]; then
-	                U_ID=${BASH_REMATCH[1]}
-	                U_NAME=${BASH_REMATCH[2]}
-                	U_HASH=${BASH_REMATCH[3]}
+		if [[ ${entry} =~ $regex ]]; then
+			U_ID=${BASH_REMATCH[1]}
+			U_NAME=${BASH_REMATCH[2]}
+			U_HASH=${BASH_REMATCH[3]}
 			SQLuser "DELETE \`account\`,\`account_access\` FROM \`account\` INNER JOIN \`account_access\` ON \`account\`.\`id\` = \`account_access\`.\`id\` WHERE \`account\`.\`id\`=${U_ID} AND \`account\`.\`username\`='${U_NAME}' AND \`account\`.\`sha_pass_hash\`='${U_HASH}' AND \`account\`.\`sessionkey\`='' AND \`account\`.\`last_login\` IS NULL;"
 		fi
 	done
